#include "byond_functions.h"

GetStringTableEntryPtr GetStringTableEntry;
SetTurfAppearancePtr SetTurfAppearance;
SetAppearancePtr SetAppearance;
SpliceAppearancePtr SpliceAppearance;
SpliceStringPtr SpliceString;
SetPixelXPtr SetPixelX;
SetPixelYPtr SetPixelY;
SetPixelWPtr SetPixelW;
SetPixelZPtr SetPixelZ;
SetMovableDirPtr SetMovableDir;
SetLocPtr SetLoc;
ToStringPtr ToString;
GetMobAppearancePtr GetMobAppearance;
GetObjAppearancePtr GetObjAppearance;
GetVariablePtr GetVariable;
AllocObjIdPtr AllocObjId;
AllocMobIdPtr AllocMobId;
ChangeTurfPtr ChangeTurf;
